// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: provision.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EC2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceType  string                 `protobuf:"bytes,1,opt,name=InstanceType,proto3" json:"InstanceType,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=Region,proto3" json:"Region,omitempty"`
	AMI           string                 `protobuf:"bytes,3,opt,name=AMI,proto3" json:"AMI,omitempty"`
	InstanceName  string                 `protobuf:"bytes,4,opt,name=InstanceName,proto3" json:"InstanceName,omitempty"`
	OpenPorts     []int32                `protobuf:"varint,5,rep,packed,name=OpenPorts,proto3" json:"OpenPorts,omitempty"`
	AWSAccessKey  string                 `protobuf:"bytes,6,opt,name=AWSAccessKey,proto3" json:"AWSAccessKey,omitempty"`
	AWSSecretKey  string                 `protobuf:"bytes,7,opt,name=AWSSecretKey,proto3" json:"AWSSecretKey,omitempty"`
	ComponentId   string                 `protobuf:"bytes,8,opt,name=ComponentId,proto3" json:"ComponentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EC2Request) Reset() {
	*x = EC2Request{}
	mi := &file_provision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EC2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EC2Request) ProtoMessage() {}

func (x *EC2Request) ProtoReflect() protoreflect.Message {
	mi := &file_provision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EC2Request.ProtoReflect.Descriptor instead.
func (*EC2Request) Descriptor() ([]byte, []int) {
	return file_provision_proto_rawDescGZIP(), []int{0}
}

func (x *EC2Request) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *EC2Request) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *EC2Request) GetAMI() string {
	if x != nil {
		return x.AMI
	}
	return ""
}

func (x *EC2Request) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *EC2Request) GetOpenPorts() []int32 {
	if x != nil {
		return x.OpenPorts
	}
	return nil
}

func (x *EC2Request) GetAWSAccessKey() string {
	if x != nil {
		return x.AWSAccessKey
	}
	return ""
}

func (x *EC2Request) GetAWSSecretKey() string {
	if x != nil {
		return x.AWSSecretKey
	}
	return ""
}

func (x *EC2Request) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

type S3Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=BucketName,proto3" json:"BucketName,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=Region,proto3" json:"Region,omitempty"`
	AWSAccessKey  string                 `protobuf:"bytes,3,opt,name=AWSAccessKey,proto3" json:"AWSAccessKey,omitempty"`
	AWSSecretKey  string                 `protobuf:"bytes,4,opt,name=AWSSecretKey,proto3" json:"AWSSecretKey,omitempty"`
	ComponentId   string                 `protobuf:"bytes,5,opt,name=ComponentId,proto3" json:"ComponentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3Request) Reset() {
	*x = S3Request{}
	mi := &file_provision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Request) ProtoMessage() {}

func (x *S3Request) ProtoReflect() protoreflect.Message {
	mi := &file_provision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Request.ProtoReflect.Descriptor instead.
func (*S3Request) Descriptor() ([]byte, []int) {
	return file_provision_proto_rawDescGZIP(), []int{1}
}

func (x *S3Request) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *S3Request) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *S3Request) GetAWSAccessKey() string {
	if x != nil {
		return x.AWSAccessKey
	}
	return ""
}

func (x *S3Request) GetAWSSecretKey() string {
	if x != nil {
		return x.AWSSecretKey
	}
	return ""
}

func (x *S3Request) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

type GitCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitCredential) Reset() {
	*x = GitCredential{}
	mi := &file_provision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitCredential) ProtoMessage() {}

func (x *GitCredential) ProtoReflect() protoreflect.Message {
	mi := &file_provision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitCredential.ProtoReflect.Descriptor instead.
func (*GitCredential) Descriptor() ([]byte, []int) {
	return file_provision_proto_rawDescGZIP(), []int{2}
}

func (x *GitCredential) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GitCredential) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReactRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ParentComponentId string                 `protobuf:"bytes,1,opt,name=ParentComponentId,proto3" json:"ParentComponentId,omitempty"`
	GitCredential     *GitCredential         `protobuf:"bytes,2,opt,name=GitCredential,proto3" json:"GitCredential,omitempty"`
	ComponentId       string                 `protobuf:"bytes,3,opt,name=ComponentId,proto3" json:"ComponentId,omitempty"`
	GitRepo           string                 `protobuf:"bytes,4,opt,name=GitRepo,proto3" json:"GitRepo,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReactRequest) Reset() {
	*x = ReactRequest{}
	mi := &file_provision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactRequest) ProtoMessage() {}

func (x *ReactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactRequest.ProtoReflect.Descriptor instead.
func (*ReactRequest) Descriptor() ([]byte, []int) {
	return file_provision_proto_rawDescGZIP(), []int{3}
}

func (x *ReactRequest) GetParentComponentId() string {
	if x != nil {
		return x.ParentComponentId
	}
	return ""
}

func (x *ReactRequest) GetGitCredential() *GitCredential {
	if x != nil {
		return x.GitCredential
	}
	return nil
}

func (x *ReactRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *ReactRequest) GetGitRepo() string {
	if x != nil {
		return x.GitRepo
	}
	return ""
}

type MySQLRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MySQLRootPassword string                 `protobuf:"bytes,1,opt,name=MySQLRootPassword,proto3" json:"MySQLRootPassword,omitempty"`
	MySQLDatabase     string                 `protobuf:"bytes,2,opt,name=MySQLDatabase,proto3" json:"MySQLDatabase,omitempty"`
	MySQLUser         string                 `protobuf:"bytes,3,opt,name=MySQLUser,proto3" json:"MySQLUser,omitempty"`
	MySQLPassword     string                 `protobuf:"bytes,4,opt,name=MySQLPassword,proto3" json:"MySQLPassword,omitempty"`
	Port              int32                  `protobuf:"varint,5,opt,name=Port,proto3" json:"Port,omitempty"`
	ParentComponentId string                 `protobuf:"bytes,6,opt,name=ParentComponentId,proto3" json:"ParentComponentId,omitempty"`
	ComponentId       string                 `protobuf:"bytes,7,opt,name=ComponentId,proto3" json:"ComponentId,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MySQLRequest) Reset() {
	*x = MySQLRequest{}
	mi := &file_provision_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MySQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySQLRequest) ProtoMessage() {}

func (x *MySQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provision_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySQLRequest.ProtoReflect.Descriptor instead.
func (*MySQLRequest) Descriptor() ([]byte, []int) {
	return file_provision_proto_rawDescGZIP(), []int{4}
}

func (x *MySQLRequest) GetMySQLRootPassword() string {
	if x != nil {
		return x.MySQLRootPassword
	}
	return ""
}

func (x *MySQLRequest) GetMySQLDatabase() string {
	if x != nil {
		return x.MySQLDatabase
	}
	return ""
}

func (x *MySQLRequest) GetMySQLUser() string {
	if x != nil {
		return x.MySQLUser
	}
	return ""
}

func (x *MySQLRequest) GetMySQLPassword() string {
	if x != nil {
		return x.MySQLPassword
	}
	return ""
}

func (x *MySQLRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *MySQLRequest) GetParentComponentId() string {
	if x != nil {
		return x.ParentComponentId
	}
	return ""
}

func (x *MySQLRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

type SpringRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ParentComponentId string                 `protobuf:"bytes,1,opt,name=ParentComponentId,proto3" json:"ParentComponentId,omitempty"`
	GitRepo           string                 `protobuf:"bytes,2,opt,name=GitRepo,proto3" json:"GitRepo,omitempty"`
	NginxPort         int32                  `protobuf:"varint,3,opt,name=NginxPort,proto3" json:"NginxPort,omitempty"`
	BuildTool         string                 `protobuf:"bytes,4,opt,name=BuildTool,proto3" json:"BuildTool,omitempty"`
	JDKVersion        string                 `protobuf:"bytes,5,opt,name=JDKVersion,proto3" json:"JDKVersion,omitempty"`
	Env               map[string]string      `protobuf:"bytes,6,rep,name=Env,proto3" json:"Env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GitCredential     *GitCredential         `protobuf:"bytes,7,opt,name=GitCredential,proto3" json:"GitCredential,omitempty"`
	DockerPort        int32                  `protobuf:"varint,8,opt,name=DockerPort,proto3" json:"DockerPort,omitempty"`
	ComponentId       string                 `protobuf:"bytes,9,opt,name=ComponentId,proto3" json:"ComponentId,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SpringRequest) Reset() {
	*x = SpringRequest{}
	mi := &file_provision_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpringRequest) ProtoMessage() {}

func (x *SpringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provision_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpringRequest.ProtoReflect.Descriptor instead.
func (*SpringRequest) Descriptor() ([]byte, []int) {
	return file_provision_proto_rawDescGZIP(), []int{5}
}

func (x *SpringRequest) GetParentComponentId() string {
	if x != nil {
		return x.ParentComponentId
	}
	return ""
}

func (x *SpringRequest) GetGitRepo() string {
	if x != nil {
		return x.GitRepo
	}
	return ""
}

func (x *SpringRequest) GetNginxPort() int32 {
	if x != nil {
		return x.NginxPort
	}
	return 0
}

func (x *SpringRequest) GetBuildTool() string {
	if x != nil {
		return x.BuildTool
	}
	return ""
}

func (x *SpringRequest) GetJDKVersion() string {
	if x != nil {
		return x.JDKVersion
	}
	return ""
}

func (x *SpringRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SpringRequest) GetGitCredential() *GitCredential {
	if x != nil {
		return x.GitCredential
	}
	return nil
}

func (x *SpringRequest) GetDockerPort() int32 {
	if x != nil {
		return x.DockerPort
	}
	return 0
}

func (x *SpringRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

type StartEC2SpringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EC2           *EC2Request            `protobuf:"bytes,1,opt,name=EC2,proto3" json:"EC2,omitempty"`
	Spring        *SpringRequest         `protobuf:"bytes,2,opt,name=Spring,proto3" json:"Spring,omitempty"`
	DeploymentID  string                 `protobuf:"bytes,3,opt,name=DeploymentID,proto3" json:"DeploymentID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartEC2SpringRequest) Reset() {
	*x = StartEC2SpringRequest{}
	mi := &file_provision_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEC2SpringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEC2SpringRequest) ProtoMessage() {}

func (x *StartEC2SpringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provision_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEC2SpringRequest.ProtoReflect.Descriptor instead.
func (*StartEC2SpringRequest) Descriptor() ([]byte, []int) {
	return file_provision_proto_rawDescGZIP(), []int{6}
}

func (x *StartEC2SpringRequest) GetEC2() *EC2Request {
	if x != nil {
		return x.EC2
	}
	return nil
}

func (x *StartEC2SpringRequest) GetSpring() *SpringRequest {
	if x != nil {
		return x.Spring
	}
	return nil
}

func (x *StartEC2SpringRequest) GetDeploymentID() string {
	if x != nil {
		return x.DeploymentID
	}
	return ""
}

type StartS3ReactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S3            *S3Request             `protobuf:"bytes,1,opt,name=S3,proto3" json:"S3,omitempty"`
	React         *ReactRequest          `protobuf:"bytes,2,opt,name=React,proto3" json:"React,omitempty"`
	DeploymentID  string                 `protobuf:"bytes,3,opt,name=DeploymentID,proto3" json:"DeploymentID,omitempty"`
	ComponentId   string                 `protobuf:"bytes,4,opt,name=ComponentId,proto3" json:"ComponentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartS3ReactRequest) Reset() {
	*x = StartS3ReactRequest{}
	mi := &file_provision_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartS3ReactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartS3ReactRequest) ProtoMessage() {}

func (x *StartS3ReactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provision_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartS3ReactRequest.ProtoReflect.Descriptor instead.
func (*StartS3ReactRequest) Descriptor() ([]byte, []int) {
	return file_provision_proto_rawDescGZIP(), []int{7}
}

func (x *StartS3ReactRequest) GetS3() *S3Request {
	if x != nil {
		return x.S3
	}
	return nil
}

func (x *StartS3ReactRequest) GetReact() *ReactRequest {
	if x != nil {
		return x.React
	}
	return nil
}

func (x *StartS3ReactRequest) GetDeploymentID() string {
	if x != nil {
		return x.DeploymentID
	}
	return ""
}

func (x *StartS3ReactRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

type StartEC2MySQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EC2           *EC2Request            `protobuf:"bytes,1,opt,name=EC2,proto3" json:"EC2,omitempty"`
	MySQL         *MySQLRequest          `protobuf:"bytes,2,opt,name=MySQL,proto3" json:"MySQL,omitempty"`
	DeploymentID  string                 `protobuf:"bytes,3,opt,name=DeploymentID,proto3" json:"DeploymentID,omitempty"`
	ComponentId   string                 `protobuf:"bytes,4,opt,name=ComponentId,proto3" json:"ComponentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartEC2MySQLRequest) Reset() {
	*x = StartEC2MySQLRequest{}
	mi := &file_provision_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEC2MySQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEC2MySQLRequest) ProtoMessage() {}

func (x *StartEC2MySQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provision_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEC2MySQLRequest.ProtoReflect.Descriptor instead.
func (*StartEC2MySQLRequest) Descriptor() ([]byte, []int) {
	return file_provision_proto_rawDescGZIP(), []int{8}
}

func (x *StartEC2MySQLRequest) GetEC2() *EC2Request {
	if x != nil {
		return x.EC2
	}
	return nil
}

func (x *StartEC2MySQLRequest) GetMySQL() *MySQLRequest {
	if x != nil {
		return x.MySQL
	}
	return nil
}

func (x *StartEC2MySQLRequest) GetDeploymentID() string {
	if x != nil {
		return x.DeploymentID
	}
	return ""
}

func (x *StartEC2MySQLRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

type ProvisionStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data          map[string]string      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionStartResponse) Reset() {
	*x = ProvisionStartResponse{}
	mi := &file_provision_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionStartResponse) ProtoMessage() {}

func (x *ProvisionStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provision_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionStartResponse.ProtoReflect.Descriptor instead.
func (*ProvisionStartResponse) Descriptor() ([]byte, []int) {
	return file_provision_proto_rawDescGZIP(), []int{9}
}

func (x *ProvisionStartResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProvisionStartResponse) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProvisionLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentID  string                 `protobuf:"bytes,1,opt,name=DeploymentID,proto3" json:"DeploymentID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionLogRequest) Reset() {
	*x = ProvisionLogRequest{}
	mi := &file_provision_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionLogRequest) ProtoMessage() {}

func (x *ProvisionLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provision_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionLogRequest.ProtoReflect.Descriptor instead.
func (*ProvisionLogRequest) Descriptor() ([]byte, []int) {
	return file_provision_proto_rawDescGZIP(), []int{10}
}

func (x *ProvisionLogRequest) GetDeploymentID() string {
	if x != nil {
		return x.DeploymentID
	}
	return ""
}

type ComponentLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentID  string                 `protobuf:"bytes,1,opt,name=DeploymentID,proto3" json:"DeploymentID,omitempty"`
	ComponentId   string                 `protobuf:"bytes,2,opt,name=ComponentId,proto3" json:"ComponentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentLogRequest) Reset() {
	*x = ComponentLogRequest{}
	mi := &file_provision_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentLogRequest) ProtoMessage() {}

func (x *ComponentLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provision_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentLogRequest.ProtoReflect.Descriptor instead.
func (*ComponentLogRequest) Descriptor() ([]byte, []int) {
	return file_provision_proto_rawDescGZIP(), []int{11}
}

func (x *ComponentLogRequest) GetDeploymentID() string {
	if x != nil {
		return x.DeploymentID
	}
	return ""
}

func (x *ComponentLogRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

type ProvisionLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentId   string                 `protobuf:"bytes,1,opt,name=ComponentId,proto3" json:"ComponentId,omitempty"`
	LogLine       string                 `protobuf:"bytes,2,opt,name=log_line,json=logLine,proto3" json:"log_line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionLog) Reset() {
	*x = ProvisionLog{}
	mi := &file_provision_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionLog) ProtoMessage() {}

func (x *ProvisionLog) ProtoReflect() protoreflect.Message {
	mi := &file_provision_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionLog.ProtoReflect.Descriptor instead.
func (*ProvisionLog) Descriptor() ([]byte, []int) {
	return file_provision_proto_rawDescGZIP(), []int{12}
}

func (x *ProvisionLog) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *ProvisionLog) GetLogLine() string {
	if x != nil {
		return x.LogLine
	}
	return ""
}

var File_provision_proto protoreflect.FileDescriptor

const file_provision_proto_rawDesc = "" +
	"\n" +
	"\x0fprovision.proto\x12\tprovision\"\x86\x02\n" +
	"\n" +
	"EC2Request\x12\"\n" +
	"\fInstanceType\x18\x01 \x01(\tR\fInstanceType\x12\x16\n" +
	"\x06Region\x18\x02 \x01(\tR\x06Region\x12\x10\n" +
	"\x03AMI\x18\x03 \x01(\tR\x03AMI\x12\"\n" +
	"\fInstanceName\x18\x04 \x01(\tR\fInstanceName\x12\x1c\n" +
	"\tOpenPorts\x18\x05 \x03(\x05R\tOpenPorts\x12\"\n" +
	"\fAWSAccessKey\x18\x06 \x01(\tR\fAWSAccessKey\x12\"\n" +
	"\fAWSSecretKey\x18\a \x01(\tR\fAWSSecretKey\x12 \n" +
	"\vComponentId\x18\b \x01(\tR\vComponentId\"\xad\x01\n" +
	"\tS3Request\x12\x1e\n" +
	"\n" +
	"BucketName\x18\x01 \x01(\tR\n" +
	"BucketName\x12\x16\n" +
	"\x06Region\x18\x02 \x01(\tR\x06Region\x12\"\n" +
	"\fAWSAccessKey\x18\x03 \x01(\tR\fAWSAccessKey\x12\"\n" +
	"\fAWSSecretKey\x18\x04 \x01(\tR\fAWSSecretKey\x12 \n" +
	"\vComponentId\x18\x05 \x01(\tR\vComponentId\"1\n" +
	"\rGitCredential\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\tR\x03Key\"\xb8\x01\n" +
	"\fReactRequest\x12,\n" +
	"\x11ParentComponentId\x18\x01 \x01(\tR\x11ParentComponentId\x12>\n" +
	"\rGitCredential\x18\x02 \x01(\v2\x18.provision.GitCredentialR\rGitCredential\x12 \n" +
	"\vComponentId\x18\x03 \x01(\tR\vComponentId\x12\x18\n" +
	"\aGitRepo\x18\x04 \x01(\tR\aGitRepo\"\x8a\x02\n" +
	"\fMySQLRequest\x12,\n" +
	"\x11MySQLRootPassword\x18\x01 \x01(\tR\x11MySQLRootPassword\x12$\n" +
	"\rMySQLDatabase\x18\x02 \x01(\tR\rMySQLDatabase\x12\x1c\n" +
	"\tMySQLUser\x18\x03 \x01(\tR\tMySQLUser\x12$\n" +
	"\rMySQLPassword\x18\x04 \x01(\tR\rMySQLPassword\x12\x12\n" +
	"\x04Port\x18\x05 \x01(\x05R\x04Port\x12,\n" +
	"\x11ParentComponentId\x18\x06 \x01(\tR\x11ParentComponentId\x12 \n" +
	"\vComponentId\x18\a \x01(\tR\vComponentId\"\xa2\x03\n" +
	"\rSpringRequest\x12,\n" +
	"\x11ParentComponentId\x18\x01 \x01(\tR\x11ParentComponentId\x12\x18\n" +
	"\aGitRepo\x18\x02 \x01(\tR\aGitRepo\x12\x1c\n" +
	"\tNginxPort\x18\x03 \x01(\x05R\tNginxPort\x12\x1c\n" +
	"\tBuildTool\x18\x04 \x01(\tR\tBuildTool\x12\x1e\n" +
	"\n" +
	"JDKVersion\x18\x05 \x01(\tR\n" +
	"JDKVersion\x123\n" +
	"\x03Env\x18\x06 \x03(\v2!.provision.SpringRequest.EnvEntryR\x03Env\x12>\n" +
	"\rGitCredential\x18\a \x01(\v2\x18.provision.GitCredentialR\rGitCredential\x12\x1e\n" +
	"\n" +
	"DockerPort\x18\b \x01(\x05R\n" +
	"DockerPort\x12 \n" +
	"\vComponentId\x18\t \x01(\tR\vComponentId\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\x15StartEC2SpringRequest\x12'\n" +
	"\x03EC2\x18\x01 \x01(\v2\x15.provision.EC2RequestR\x03EC2\x120\n" +
	"\x06Spring\x18\x02 \x01(\v2\x18.provision.SpringRequestR\x06Spring\x12\"\n" +
	"\fDeploymentID\x18\x03 \x01(\tR\fDeploymentID\"\xb0\x01\n" +
	"\x13StartS3ReactRequest\x12$\n" +
	"\x02S3\x18\x01 \x01(\v2\x14.provision.S3RequestR\x02S3\x12-\n" +
	"\x05React\x18\x02 \x01(\v2\x17.provision.ReactRequestR\x05React\x12\"\n" +
	"\fDeploymentID\x18\x03 \x01(\tR\fDeploymentID\x12 \n" +
	"\vComponentId\x18\x04 \x01(\tR\vComponentId\"\xb4\x01\n" +
	"\x14StartEC2MySQLRequest\x12'\n" +
	"\x03EC2\x18\x01 \x01(\v2\x15.provision.EC2RequestR\x03EC2\x12-\n" +
	"\x05MySQL\x18\x02 \x01(\v2\x17.provision.MySQLRequestR\x05MySQL\x12\"\n" +
	"\fDeploymentID\x18\x03 \x01(\tR\fDeploymentID\x12 \n" +
	"\vComponentId\x18\x04 \x01(\tR\vComponentId\"\xaa\x01\n" +
	"\x16ProvisionStartResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12?\n" +
	"\x04data\x18\x02 \x03(\v2+.provision.ProvisionStartResponse.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x13ProvisionLogRequest\x12\"\n" +
	"\fDeploymentID\x18\x01 \x01(\tR\fDeploymentID\"[\n" +
	"\x13ComponentLogRequest\x12\"\n" +
	"\fDeploymentID\x18\x01 \x01(\tR\fDeploymentID\x12 \n" +
	"\vComponentId\x18\x02 \x01(\tR\vComponentId\"K\n" +
	"\fProvisionLog\x12 \n" +
	"\vComponentId\x18\x01 \x01(\tR\vComponentId\x12\x19\n" +
	"\blog_line\x18\x02 \x01(\tR\alogLine2\xb8\x03\n" +
	"\x13ProvisioningService\x12U\n" +
	"\x0eStartEC2Spring\x12 .provision.StartEC2SpringRequest\x1a!.provision.ProvisionStartResponse\x12S\n" +
	"\rStartEC2MySQL\x12\x1f.provision.StartEC2MySQLRequest\x1a!.provision.ProvisionStartResponse\x12Q\n" +
	"\fStartS3React\x12\x1e.provision.StartS3ReactRequest\x1a!.provision.ProvisionStartResponse\x12P\n" +
	"\x13StreamProvisionLogs\x12\x1e.provision.ProvisionLogRequest\x1a\x17.provision.ProvisionLog0\x01\x12P\n" +
	"\x13StreamComponentLogs\x12\x1e.provision.ComponentLogRequest\x1a\x17.provision.ProvisionLog0\x01B\bZ\x06proto/b\x06proto3"

var (
	file_provision_proto_rawDescOnce sync.Once
	file_provision_proto_rawDescData []byte
)

func file_provision_proto_rawDescGZIP() []byte {
	file_provision_proto_rawDescOnce.Do(func() {
		file_provision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provision_proto_rawDesc), len(file_provision_proto_rawDesc)))
	})
	return file_provision_proto_rawDescData
}

var file_provision_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_provision_proto_goTypes = []any{
	(*EC2Request)(nil),             // 0: provision.EC2Request
	(*S3Request)(nil),              // 1: provision.S3Request
	(*GitCredential)(nil),          // 2: provision.GitCredential
	(*ReactRequest)(nil),           // 3: provision.ReactRequest
	(*MySQLRequest)(nil),           // 4: provision.MySQLRequest
	(*SpringRequest)(nil),          // 5: provision.SpringRequest
	(*StartEC2SpringRequest)(nil),  // 6: provision.StartEC2SpringRequest
	(*StartS3ReactRequest)(nil),    // 7: provision.StartS3ReactRequest
	(*StartEC2MySQLRequest)(nil),   // 8: provision.StartEC2MySQLRequest
	(*ProvisionStartResponse)(nil), // 9: provision.ProvisionStartResponse
	(*ProvisionLogRequest)(nil),    // 10: provision.ProvisionLogRequest
	(*ComponentLogRequest)(nil),    // 11: provision.ComponentLogRequest
	(*ProvisionLog)(nil),           // 12: provision.ProvisionLog
	nil,                            // 13: provision.SpringRequest.EnvEntry
	nil,                            // 14: provision.ProvisionStartResponse.DataEntry
}
var file_provision_proto_depIdxs = []int32{
	2,  // 0: provision.ReactRequest.GitCredential:type_name -> provision.GitCredential
	13, // 1: provision.SpringRequest.Env:type_name -> provision.SpringRequest.EnvEntry
	2,  // 2: provision.SpringRequest.GitCredential:type_name -> provision.GitCredential
	0,  // 3: provision.StartEC2SpringRequest.EC2:type_name -> provision.EC2Request
	5,  // 4: provision.StartEC2SpringRequest.Spring:type_name -> provision.SpringRequest
	1,  // 5: provision.StartS3ReactRequest.S3:type_name -> provision.S3Request
	3,  // 6: provision.StartS3ReactRequest.React:type_name -> provision.ReactRequest
	0,  // 7: provision.StartEC2MySQLRequest.EC2:type_name -> provision.EC2Request
	4,  // 8: provision.StartEC2MySQLRequest.MySQL:type_name -> provision.MySQLRequest
	14, // 9: provision.ProvisionStartResponse.data:type_name -> provision.ProvisionStartResponse.DataEntry
	6,  // 10: provision.ProvisioningService.StartEC2Spring:input_type -> provision.StartEC2SpringRequest
	8,  // 11: provision.ProvisioningService.StartEC2MySQL:input_type -> provision.StartEC2MySQLRequest
	7,  // 12: provision.ProvisioningService.StartS3React:input_type -> provision.StartS3ReactRequest
	10, // 13: provision.ProvisioningService.StreamProvisionLogs:input_type -> provision.ProvisionLogRequest
	11, // 14: provision.ProvisioningService.StreamComponentLogs:input_type -> provision.ComponentLogRequest
	9,  // 15: provision.ProvisioningService.StartEC2Spring:output_type -> provision.ProvisionStartResponse
	9,  // 16: provision.ProvisioningService.StartEC2MySQL:output_type -> provision.ProvisionStartResponse
	9,  // 17: provision.ProvisioningService.StartS3React:output_type -> provision.ProvisionStartResponse
	12, // 18: provision.ProvisioningService.StreamProvisionLogs:output_type -> provision.ProvisionLog
	12, // 19: provision.ProvisioningService.StreamComponentLogs:output_type -> provision.ProvisionLog
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_provision_proto_init() }
func file_provision_proto_init() {
	if File_provision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provision_proto_rawDesc), len(file_provision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provision_proto_goTypes,
		DependencyIndexes: file_provision_proto_depIdxs,
		MessageInfos:      file_provision_proto_msgTypes,
	}.Build()
	File_provision_proto = out.File
	file_provision_proto_goTypes = nil
	file_provision_proto_depIdxs = nil
}
