version: '3.8'
services:
  test-db:
    image: mysql:8.0
    container_name: pado-test-mysql
    environment:
      MYSQL_DATABASE: pado_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306"
